### ISSUE TITLE
libompitrace does not check use of MPI_DATATYPE_NULL when calling PMPI_Type_get_name and causes MPI_ERR_TYPE 

### ISSUE THREAD

**Issue by minsii** [open-mpi/ompi#10028]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
We use 4.0.2 but the same issue exists in master branch.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Built from source of 4.0.2 release tarball

### Please describe the system on which you are running

(confirmed that the issue is irrelevant to specific OS)
* Operating system/version: 
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

We use libompitrace with NCCL-tests which internally uses MPI_DATATYPE_NULL with MPI_Allgather (see https://github.com/NVIDIA/nccl-tests/blob/master/src/common.cu#L1022). This is a legal use of MPI_DATATYPE_NULL. However, when we enable libompitrace with OpenMPI, it reports error below.
```
*** An error occurred in MPI_Type_get_name
*** reported by process [1728118785,0]
*** on communicator MPI_COMM_WORLD
*** MPI_ERR_TYPE: invalid datatype
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```

By checking the code of libompitrace/allgather.c, we found that it does not check whether the datatype is MPI_DATATYPE_NULL before calling PMPI_Type_get_name, thus caused this error.

**Comment by jsquyres** [comment]
@bosilca made #10029 to fix the issue; see the discussion over there.

**Comment by minsii** [comment]
@jsquyres Thank you for linking to the fix PR.

**Comment by jsquyres** [comment]
Fixed in master, v4.0.x, and v4.1.x.  Will be included in any next release from the v4.0.x and v4.1.x branches.  PR #10051 ended up removing libompitrace from master, and #10054 removed it from the v5.0.x branch.  Hence, libompitrace will not be included in the v5.0.0 release.

Since this issue has been resolved on all the relevant release branches, I'm going to close the bug.

Thanks for reporting the issue!
